
DROP TABLE IF EXISTS temp_card_templates;
CREATE TABLE IF NOT EXISTS "temp_card_templates" (
    "order_del" TEXT,
    "template_id_gen" TEXT,
    "name" TEXT,
    "pitch" INT,
    "cost" INT,
    "cost_var" TEXT,
    "power" INT,
    "power_var" TEXT,
    "defense" INT,
    "defense_var" INT,
    "intellect" INT,
    "life" INT,
    "handedness" INT,
    "legendary" BOOLEAN,
    "class" TEXT,
    "type" TEXT,
    "subtypes" TEXT,
    "specialization" TEXT
);
INSERT INTO "temp_card_templates" VALUES
    ('A001','ira-crimson-haze','Ira, Crimson Haze',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,20,NULL,'N','Ninja','Hero','Young',NULL),
    ('A002','edge-of-autumn','Edge of Autumn',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,2,'N','Ninja','Weapon','Sword',NULL),
    ('A003','whirling-mist-blossom-2','Whirling Mist Blossom',2,1,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack','Ira'),
    ('A004','salt-the-wound-2','Salt the Wound',2,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('A005','bittering-thorns-2','Bittering Thorns',2,1,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('A006','torrent-of-tempo-1','Torrent of Tempo',1,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('A007','flying-kick-1','Flying Kick',1,2,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('A008','brutal-assault-3','Brutal Assault',3,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('A009','lunging-press-3','Lunging Press',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Attack Reaction',NULL,NULL),
    ('A010','springboard-somersault-2','Springboard Somersault',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Defense Reaction',NULL,NULL),
    ('B000','heart-of-fyendal-3','Heart of Fyendal',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'t','Generic','Resource','Gem',NULL),
    ('B001','rhinar-reckless-rampage','Rhinar, Reckless Rampage',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,40,NULL,'N','Brute','Hero',NULL,NULL),
    ('B002','rhinar','Rhinar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,20,NULL,'N','Brute','Hero','Young',NULL),
    ('B003','romping-club','Romping Club',NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,NULL,2,'N','Brute','Weapon','Club',NULL),
    ('B004','scabskin-leathers','Scabskin Leathers',NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Brute','Equipment','Legs',NULL),
    ('B005','barkbone-strapping','Barkbone Strapping',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Brute','Equipment','Chest',NULL),
    ('B006','alpha-rampage-1','Alpha Rampage',1,3,NULL,9,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack','Rhinar'),
    ('B007','bloodrush-bellow-2','Bloodrush Bellow',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,NULL),
    ('B008','reckless-swing-3','Reckless Swing',3,0,NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,'N','Brute','Defense Reaction',NULL,NULL),
    ('B009','sand-sketched-plan-3','Sand Sketched Plan',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,'Rhinar'),
    ('B010','bone-head-barrier-2','Bone Head Barrier',2,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Brute','Instant',NULL,NULL),
    ('B011','breakneck-battery-1','Breakneck Battery',1,2,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B012','breakneck-battery-2','Breakneck Battery',2,2,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B013','breakneck-battery-3','Breakneck Battery',3,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B014','savage-feast-1','Savage Feast',1,1,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B015','savage-feast-2','Savage Feast',2,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B016','savage-feast-3','Savage Feast',3,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B017','barraging-beatdown-1','Barraging Beatdown',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,NULL),
    ('B018','barraging-beatdown-2','Barraging Beatdown',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,NULL),
    ('B019','barraging-beatdown-3','Barraging Beatdown',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,NULL),
    ('B020','savage-swing-1','Savage Swing',1,1,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B021','savage-swing-2','Savage Swing',2,1,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B022','savage-swing-3','Savage Swing',3,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B023','pack-hunt-1','Pack Hunt',1,2,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B024','pack-hunt-2','Pack Hunt',2,2,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B025','pack-hunt-3','Pack Hunt',3,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B026','smash-instinct-1','Smash Instinct',1,3,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B027','smash-instinct-2','Smash Instinct',2,3,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B028','smash-instinct-3','Smash Instinct',3,3,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B029','wrecker-romp-1','Wrecker Romp',1,2,NULL,8,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B030','wrecker-romp-2','Wrecker Romp',2,2,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B031','wrecker-romp-3','Wrecker Romp',3,2,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('B032','awakening-bellow-1','Awakening Bellow',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,NULL),
    ('B033','awakening-bellow-2','Awakening Bellow',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,NULL),
    ('B034','awakening-bellow-3','Awakening Bellow',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,NULL),
    ('B035','primeval-bellow-1','Primeval Bellow',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,NULL),
    ('B036','primeval-bellow-2','Primeval Bellow',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,NULL),
    ('B037','primeval-bellow-3','Primeval Bellow',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,NULL),
    ('B038','bravo-showstopper','Bravo, Showstopper',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,40,NULL,'N','Guardian','Hero',NULL,NULL),
    ('B039','bravo','Bravo',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,20,NULL,'N','Guardian','Hero','Young',NULL),
    ('B040','anothos','Anothos',NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,NULL,2,'N','Guardian','Weapon','Club',NULL),
    ('B041','tectonic-plating','Tectonic Plating',NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Guardian','Equipment','Chest',NULL),
    ('B042','helm-of-isens-peak','Helm of Isen''s Peak',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Guardian','Equipment','Head',NULL),
    ('B043','crippling-crush-1','Crippling Crush',1,7,NULL,11,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack','Bravo'),
    ('B044','spinal-crush-1','Spinal Crush',1,5,NULL,9,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B045','cranial-crush-3','Cranial Crush',3,6,NULL,8,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B046','forged-for-war-2','Forged for War',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('B047','show-time-3','Show Time!',3,3,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura','Bravo'),
    ('B048','disable-1','Disable',1,5,NULL,9,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B049','disable-2','Disable',2,5,NULL,8,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B050','disable-3','Disable',3,5,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B051','staunch-response-1','Staunch Response',1,2,NULL,NULL,NULL,7,NULL,NULL,NULL,NULL,'N','Guardian','Defense Reaction',NULL,NULL),
    ('B052','staunch-response-2','Staunch Response',2,2,NULL,NULL,NULL,6,NULL,NULL,NULL,NULL,'N','Guardian','Defense Reaction',NULL,NULL),
    ('B053','staunch-response-3','Staunch Response',3,2,NULL,NULL,NULL,5,NULL,NULL,NULL,NULL,'N','Guardian','Defense Reaction',NULL,NULL),
    ('B054','blessing-of-deliverance-1','Blessing of Deliverance',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('B055','blessing-of-deliverance-2','Blessing of Deliverance',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('B056','blessing-of-deliverance-3','Blessing of Deliverance',3,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('B057','buckling-blow-1','Buckling Blow',1,4,NULL,8,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B058','buckling-blow-2','Buckling Blow',2,4,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B059','buckling-blow-3','Buckling Blow',3,4,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B060','cartilage-crush-1','Cartilage Crush',1,3,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B061','cartilage-crush-2','Cartilage Crush',2,3,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B062','cartilage-crush-3','Cartilage Crush',3,3,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B063','crush-confidence-1','Crush Confidence',1,3,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B064','crush-confidence-2','Crush Confidence',2,3,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B065','crush-confidence-3','Crush Confidence',3,3,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B066','debilitate-1','Debilitate',1,4,NULL,8,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B067','debilitate-2','Debilitate',2,4,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B068','debilitate-3','Debilitate',3,4,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('B069','emerging-power-1','Emerging Power',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('B070','emerging-power-2','Emerging Power',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('B071','emerging-power-3','Emerging Power',3,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('B072','stonewall-confidence-1','Stonewall Confidence',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('B073','stonewall-confidence-2','Stonewall Confidence',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('B074','stonewall-confidence-3','Stonewall Confidence',3,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('B075','seismic-surge','Seismic Surge',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Guardian','Token','Aura',NULL),
    ('B076','katsu-the-wanderer','Katsu, the Wanderer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,40,NULL,'N','Ninja','Hero',NULL,NULL),
    ('B077','katsu','Katsu',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,20,NULL,'N','Ninja','Hero','Young',NULL),
    ('B078','harmonized-kodachi','Harmonized Kodachi',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,1,'N','Ninja','Weapon','Dagger',NULL),
    ('B079','mask-of-momentum','Mask of Momentum',NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Equipment','Head',NULL),
    ('B080','breaking-scales','Breaking Scales',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Ninja','Equipment','Legs',NULL),
    ('B081','lord-of-wind-3','Lord of Wind',3,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack','Katsu'),
    ('B082','ancestral-empowerment-1','Ancestral Empowerment',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Attack Reaction',NULL,NULL),
    ('B083','mugenshi-release-2','Mugenshi: RELEASE',2,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack','Katsu'),
    ('B084','hurricane-technique-2','Hurricane Technique',2,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B085','pounding-gale-1','Pounding Gale',1,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B086','fluster-fist-1','Fluster Fist',1,0,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B087','fluster-fist-2','Fluster Fist',2,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B088','fluster-fist-3','Fluster Fist',3,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B089','blackout-kick-1','Blackout Kick',1,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B090','blackout-kick-2','Blackout Kick',2,1,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B091','blackout-kick-3','Blackout Kick',3,1,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B092','flic-flak-1','Flic Flak',1,0,NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,'N','Ninja','Defense Reaction',NULL,NULL),
    ('B093','flic-flak-2','Flic Flak',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Defense Reaction',NULL,NULL),
    ('B094','flic-flak-3','Flic Flak',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Defense Reaction',NULL,NULL),
    ('B095','open-the-center-1','Open the Center',1,2,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B096','open-the-center-2','Open the Center',2,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B097','open-the-center-3','Open the Center',3,2,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B098','head-jab-1','Head Jab',1,0,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B099','head-jab-2','Head Jab',2,0,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B100','head-jab-3','Head Jab',3,0,NULL,1,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B101','leg-tap-1','Leg Tap',1,1,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B102','leg-tap-2','Leg Tap',2,1,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B103','leg-tap-3','Leg Tap',3,1,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B104','rising-knee-thrust-1','Rising Knee Thrust',1,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B105','rising-knee-thrust-2','Rising Knee Thrust',2,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B106','rising-knee-thrust-3','Rising Knee Thrust',3,0,NULL,1,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B107','surging-strike-1','Surging Strike',1,2,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B108','surging-strike-2','Surging Strike',2,2,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B109','surging-strike-3','Surging Strike',3,2,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B110','whelming-gustwave-1','Whelming Gustwave',1,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B111','whelming-gustwave-2','Whelming Gustwave',2,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B112','whelming-gustwave-3','Whelming Gustwave',3,0,NULL,1,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('B113','dorinthea-ironsong','Dorinthea Ironsong',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,40,NULL,'N','Warrior','Hero',NULL,NULL),
    ('B114','dorinthea','Dorinthea',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,20,NULL,'N','Warrior','Hero','Young',NULL),
    ('B115','dawnblade','Dawnblade',NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL,2,'N','Warrior','Weapon','Sword',NULL),
    ('B116','braveforge-bracers','Braveforge Bracers',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Warrior','Equipment','Arms',NULL),
    ('B117','refraction-bolters','Refraction Bolters',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Warrior','Equipment','Legs',NULL),
    ('B118','glint-the-quicksilver-3','Glint the Quicksilver',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B119','steelblade-supremacy-1','Steelblade Supremacy',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,'Dorinthea'),
    ('B120','rout-1','Rout',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B121','singing-steelblade-2','Singing Steelblade',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,'Dorinthea'),
    ('B122','ironsong-determination-2','Ironsong Determination',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B123','overpower-1','Overpower',1,3,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B124','overpower-2','Overpower',2,3,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B125','overpower-3','Overpower',3,3,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B126','steelblade-shunt-1','Steelblade Shunt',1,1,NULL,NULL,NULL,6,NULL,NULL,NULL,NULL,'N','Warrior','Defense Reaction',NULL,NULL),
    ('B127','steelblade-shunt-2','Steelblade Shunt',2,1,NULL,NULL,NULL,5,NULL,NULL,NULL,NULL,'N','Warrior','Defense Reaction',NULL,NULL),
    ('B128','steelblade-shunt-3','Steelblade Shunt',3,1,NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,'N','Warrior','Defense Reaction',NULL,NULL),
    ('B129','warriors-valor-1','Warrior''s Valor',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B130','warriors-valor-2','Warrior''s Valor',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B131','warriors-valor-3','Warrior''s Valor',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B132','ironsong-response-1','Ironsong Response',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B133','ironsong-response-2','Ironsong Response',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B134','ironsong-response-3','Ironsong Response',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B135','biting-blade-1','Biting Blade',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B136','biting-blade-2','Biting Blade',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B137','biting-blade-3','Biting Blade',3,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B138','stroke-of-foresight-1','Stroke of Foresight',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B139','stroke-of-foresight-2','Stroke of Foresight',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B140','stroke-of-foresight-3','Stroke of Foresight',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('B141','sharpen-steel-1','Sharpen Steel',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B142','sharpen-steel-2','Sharpen Steel',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B143','sharpen-steel-3','Sharpen Steel',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B144','driving-blade-1','Driving Blade',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B145','driving-blade-2','Driving Blade',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B146','driving-blade-3','Driving Blade',3,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B147','natures-path-pilgrimage-1','Nature''s Path Pilgrimage',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B148','natures-path-pilgrimage-2','Nature''s Path Pilgrimage',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B149','natures-path-pilgrimage-3','Nature''s Path Pilgrimage',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('B150','fyendals-spring-tunic','Fyendal''s Spring Tunic',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Chest',NULL),
    ('B151','hope-merchants-hood','Hope Merchant''s Hood',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Head',NULL),
    ('B152','heartened-cross-strap','Heartened Cross Strap',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Chest',NULL),
    ('B153','goliath-gauntlet','Goliath Gauntlet',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Arms',NULL),
    ('B154','snapdragon-scalers','Snapdragon Scalers',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Legs',NULL),
    ('B155','ironrot-helm','Ironrot Helm',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Head',NULL),
    ('B156','ironrot-plate','Ironrot Plate',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Chest',NULL),
    ('B157','ironrot-gauntlet','Ironrot Gauntlet',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Arms',NULL),
    ('B158','ironrot-legs','Ironrot Legs',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Legs',NULL),
    ('B159','enlightened-strike-1','Enlightened Strike',1,0,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B160','tome-of-fyendal-2','Tome of Fyendal',2,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('B161','last-ditch-effort-3','Last Ditch Effort',3,3,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B162','crazy-brew-3','Crazy Brew',3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Action','Item',NULL),
    ('B163','rememberance-2','Rememberance',2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('B164','drone-of-brutality-1','Drone of Brutality',1,2,NULL,6,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B165','drone-of-brutality-2','Drone of Brutality',2,2,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B166','drone-of-brutality-3','Drone of Brutality',3,2,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B167','snatch-1','Snatch',1,0,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B168','snatch-2','Snatch',2,0,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B169','snatch-3','Snatch',3,0,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B170','energy-potion-3','Energy Potion',3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Action','Item',NULL),
    ('B171','potion-of-strength-3','Potion of Strength',3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Action','Item',NULL),
    ('B172','timesnap-potion-3','Timesnap Potion',3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Action','Item',NULL),
    ('B173','sigil-of-solace-1','Sigil of Solace',1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('B174','sigil-of-solace-2','Sigil of Solace',2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('B175','sigil-of-solace-3','Sigil of Solace',3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('B176','barraging-brawnhide-1','Barraging Brawnhide',1,3,NULL,7,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B177','barraging-brawnhide-2','Barraging Brawnhide',2,3,NULL,6,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B178','barraging-brawnhide-3','Barraging Brawnhide',3,3,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B179','demolition-crew-1','Demolition Crew',1,2,NULL,6,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B180','demolition-crew-2','Demolition Crew',2,2,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B181','demolition-crew-3','Demolition Crew',3,2,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B182','flock-of-feather-walkers-1','Flock of Feather Walkers',1,1,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B183','flock-of-feather-walkers-2','Flock of Feather Walkers',2,1,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B184','flock-of-feather-walkers-3','Flock of Feather Walkers',3,1,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B185','nimble-strike-1','Nimble Strike',1,1,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B186','nimble-strike-2','Nimble Strike',2,1,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B187','nimble-strike-3','Nimble Strike',3,1,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B188','raging-onslaught-1','Raging Onslaught',1,3,NULL,7,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B189','raging-onslaught-2','Raging Onslaught',2,3,NULL,6,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B190','raging-onslaught-3','Raging Onslaught',3,3,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B191','scar-for-a-scar-1','Scar for a Scar',1,0,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B192','scar-for-a-scar-2','Scar for a Scar',2,0,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B193','scar-for-a-scar-3','Scar for a Scar',3,0,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B194','scour-the-battlescape-1','Scour the Battlescape',1,0,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B195','scour-the-battlescape-2','Scour the Battlescape',2,0,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B196','scour-the-battlescape-3','Scour the Battlescape',3,0,NULL,1,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B197','regurgitating-slog-1','Regurgitating Slog',1,2,NULL,6,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B198','regurgitating-slog-2','Regurgitating Slog',2,2,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B199','regurgitating-slog-3','Regurgitating Slog',3,2,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B200','wounded-bull-1','Wounded Bull',1,3,NULL,7,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B201','wounded-bull-2','Wounded Bull',2,3,NULL,6,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B202','wounded-bull-3','Wounded Bull',3,3,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B203','wounding-blow-1','Wounding Blow',1,0,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B204','wounding-blow-2','Wounding Blow',2,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B205','wounding-blow-3','Wounding Blow',3,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('B206','pummel-1','Pummel',1,2,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Attack Reaction',NULL,NULL),
    ('B207','pummel-2','Pummel',2,2,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Attack Reaction',NULL,NULL),
    ('B208','pummel-3','Pummel',3,2,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Attack Reaction',NULL,NULL),
    ('B209','razor-reflex-1','Razor Reflex',1,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Attack Reaction',NULL,NULL),
    ('B210','razor-reflex-2','Razor Reflex',2,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Attack Reaction',NULL,NULL),
    ('B211','razor-reflex-3','Razor Reflex',3,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Attack Reaction',NULL,NULL),
    ('B212','unmovable-1','Unmovable',1,3,NULL,NULL,NULL,7,NULL,NULL,NULL,NULL,'N','Generic','Defense Reaction',NULL,NULL),
    ('B213','unmovable-2','Unmovable',2,3,NULL,NULL,NULL,6,NULL,NULL,NULL,NULL,'N','Generic','Defense Reaction',NULL,NULL),
    ('B214','unmovable-3','Unmovable',3,3,NULL,NULL,NULL,5,NULL,NULL,NULL,NULL,'N','Generic','Defense Reaction',NULL,NULL),
    ('B215','sink-below-1','Sink Below',1,0,NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,'N','Generic','Defense Reaction',NULL,NULL),
    ('B216','sink-below-2','Sink Below',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Defense Reaction',NULL,NULL),
    ('B217','sink-below-3','Sink Below',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Defense Reaction',NULL,NULL),
    ('B218','nimblism-1','Nimblism',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('B219','nimblism-2','Nimblism',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('B220','nimblism-3','Nimblism',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('B221','sloggism-1','Sloggism',1,3,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('B222','sloggism-2','Sloggism',2,3,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('B223','sloggism-3','Sloggism',3,3,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('B224','cracked-bauble-2','Cracked Bauble',2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Resource',NULL,NULL),
    ('B225','quicken','Quicken',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Token','Aura',NULL),
    ('C000','eye-of-ophidia-3','Eye of Ophidia',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'t','Generic','Resource','Gem',NULL),
    ('C001','dash-inventor-extraordinaire','Dash, Inventor Extraordinaire',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,40,NULL,'N','Mechanologist','Hero',NULL,NULL),
    ('C002','dash','Dash',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,20,NULL,'N','Mechanologist','Hero','Young',NULL),
    ('C003','teklo-plasma-pistol','Teklo Plasma Pistol',NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,2,'N','Mechanologist','Weapon','Pistol',NULL),
    ('C004','teklo-foundry-heart','Teklo Foundry Heart',NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Mechanologist','Equipment','Chest',NULL),
    ('C005','achilles-accelerator','Achilles Accelerator',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Mechanologist','Equipment','Legs',NULL),
    ('C006','high-octane-1','High Octane',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action',NULL,NULL),
    ('C007','teklo-core-3','Teklo Core',3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Item','Dash'),
    ('C008','maximum-velocity-1','Maximum Velocity',1,2,NULL,10,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C009','spark-of-genius-2','Spark of Genius',2,0,'XX',NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action',NULL,'Dash'),
    ('C010','induction-chamber-1','Induction Chamber',1,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Item',NULL),
    ('C011','pedal-to-the-metal-1','Pedal to the Metal',1,2,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C012','pedal-to-the-metal-2','Pedal to the Metal',2,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C013','pedal-to-the-metal-3','Pedal to the Metal',3,2,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL);
INSERT INTO "temp_card_templates" VALUES
    ('C014','pour-the-mold-1','Pour the Mold',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action',NULL,NULL),
    ('C015','pour-the-mold-2','Pour the Mold',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action',NULL,NULL),
    ('C016','pour-the-mold-3','Pour the Mold',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action',NULL,NULL),
    ('C017','aether-sink-2','Aether Sink',2,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Item',NULL),
    ('C018','cognition-nodes-3','Cognition Nodes',3,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Item',NULL),
    ('C019','convection-amplifier-1','Convection Amplifier',1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Item',NULL),
    ('C020','over-loop-1','Over Loop',1,2,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C021','over-loop-2','Over Loop',2,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C022','over-loop-3','Over Loop',3,2,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C023','throttle-1','Throttle',1,2,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C024','throttle-2','Throttle',2,2,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C025','throttle-3','Throttle',3,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C026','zero-to-sixty-1','Zero to Sixty',1,0,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C027','zero-to-sixty-2','Zero to Sixty',2,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C028','zero-to-sixty-3','Zero to Sixty',3,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C029','zipper-hit-1','Zipper Hit',1,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C030','zipper-hit-2','Zipper Hit',2,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C031','zipper-hit-3','Zipper Hit',3,1,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('C032','locked-and-loaded-1','Locked and Loaded',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action',NULL,NULL),
    ('C033','locked-and-loaded-2','Locked and Loaded',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action',NULL,NULL),
    ('C034','locked-and-loaded-3','Locked and Loaded',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action',NULL,NULL),
    ('C035','dissipation-shield-2','Dissipation Shield',2,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Item',NULL),
    ('C036','hyper-driver-1','Hyper Driver',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Item',NULL),
    ('C037','optekal-monocle-3','Optekal Monocle',3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Item',NULL),
    ('C038','azalea-ace-in-the-hole','Azalea, Ace in the Hole',NULL,NULL,NULL,NULL,NULL,NULL,NULL,20,40,NULL,'N','Ranger','Hero',NULL,NULL),
    ('C039','azalea','Azalea',NULL,NULL,NULL,NULL,NULL,NULL,NULL,20,40,NULL,'N','Ranger','Hero','Young',NULL),
    ('C040','death-dealer','Death Dealer',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,'N','Ranger','Weapon','Bow',NULL),
    ('C041','skullbone-crosswrap','Skullbone Crosswrap',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Ranger','Equipment','Head',NULL),
    ('C042','bulls-eye-bracers','Bull''s Eye Bracers',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Ranger','Equipment','Arms',NULL),
    ('C043','red-in-the-ledger-1','Red in the Ledger',1,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack','Azalea'),
    ('C044','three-of-a-kind-1','Three of a Kind',1,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('C045','endless-arrows-1','Endless Arrows',1,0,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C046','nock-the-deathwhistle-3','Nock the Deathwhistle',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,'Azalea'),
    ('C047','rapid-fire-2','Rapid Fire',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('C048','take-cover-1','Take Cover',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Defense Reaction',NULL,NULL),
    ('C049','take-cover-2','Take Cover',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Defense Reaction',NULL,NULL),
    ('C050','take-cover-3','Take Cover',3,0,NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,'N','Ranger','Defense Reaction',NULL,NULL),
    ('C051','silver-the-tip-1','Silver the Tip',1,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('C052','silver-the-tip-2','Silver the Tip',2,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('C053','silver-the-tip-3','Silver the Tip',3,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('C054','take-aim-1','Take Aim',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('C055','take-aim-2','Take Aim',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('C056','take-aim-3','Take Aim',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('C057','head-shot-1','Head Shot',1,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C058','head-shot-2','Head Shot',2,1,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C059','head-shot-3','Head Shot',3,1,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C060','hamstring-shot-1','Hamstring Shot',1,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C061','hamstring-shot-2','Hamstring Shot',2,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C062','hamstring-shot-3','Hamstring Shot',3,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C063','ridge-rider-shot-1','Ridge Rider Shot',1,0,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C064','ridge-rider-shot-2','Ridge Rider Shot',2,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C065','ridge-rider-shot-3','Ridge Rider Shot',3,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C066','salvage-shot-1','Salvage Shot',1,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C067','salvage-shot-2','Salvage Shot',2,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C068','salvage-shot-3','Salvage Shot',3,1,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C069','searing-shot-1','Searing Shot',1,0,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C070','searing-shot-2','Searing Shot',2,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C071','searing-shot-3','Searing Shot',3,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C072','sic-em-shot-1','Sic ''Em Shot',1,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C073','sic-em-shot-2','Sic ''Em Shot',2,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C074','sic-em-shot-3','Sic ''Em Shot',3,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('C075','viserai-rune-blood','Viserai, Rune Blood',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,40,NULL,'N','Runeblade','Hero',NULL,NULL),
    ('C076','viserai','Viserai',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,20,NULL,'N','Runeblade','Hero','Young',NULL),
    ('C077','nebula-blade','Nebula Blade',NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,2,'N','Runeblade','Weapon','Sword',NULL),
    ('C078','grasp-of-the-arknight','Grasp of the Arknight',NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Equipment','Arms',NULL),
    ('C079','crown-of-dichotomy','Crown of Dichotomy',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Runeblade','Equipment','Head',NULL),
    ('C080','arknight-ascendancy-1','Arknight Ascendancy',1,6,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack','Viserai'),
    ('C081','mordred-tide-1','Mordred Tide',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('C082','ninth-blade-of-the-blood-oath-2','Ninth Blade of the Blood Oath',2,9,NULL,9,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C083','become-the-arknight-3','Become the Arknight',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,'Viserai'),
    ('C084','tome-of-the-arknight-3','Tome of the Arknight',3,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('C085','spellblade-assault-1','Spellblade Assault',1,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C086','spellblade-assault-2','Spellblade Assault',2,2,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C087','spellblade-assault-3','Spellblade Assault',3,2,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C088','reduce-to-runechant-1','Reduce to Runechant',1,1,NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,'N','Runeblade','Defense Reaction',NULL,NULL),
    ('C089','reduce-to-runechant-2','Reduce to Runechant',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Defense Reaction',NULL,NULL),
    ('C090','reduce-to-runechant-3','Reduce to Runechant',3,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Defense Reaction',NULL,NULL),
    ('C091','oath-of-the-arknight-1','Oath of the Arknight',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('C092','oath-of-the-arknight-2','Oath of the Arknight',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('C093','oath-of-the-arknight-3','Oath of the Arknight',3,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('C094','amplify-the-arknight-1','Amplify the Arknight',1,3,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C095','amplify-the-arknight-2','Amplify the Arknight',2,3,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C096','amplify-the-arknight-3','Amplify the Arknight',3,3,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C097','drawn-to-the-dark-dimension-1','Drawn to the Dark Dimension',1,2,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C098','drawn-to-the-dark-dimension-2','Drawn to the Dark Dimension',2,2,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C099','drawn-to-the-dark-dimension-3','Drawn to the Dark Dimension',3,2,NULL,1,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C100','rune-flash-1','Rune Flash',1,3,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C101','rune-flash-2','Rune Flash',2,3,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C102','rune-flash-3','Rune Flash',3,3,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C103','spellblade-strike-1','Spellblade Strike',1,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C104','spellblade-strike-2','Spellblade Strike',2,1,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C105','spellblade-strike-3','Spellblade Strike',3,1,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('C106','bloodspill-invocation-1','Bloodspill Invocation',1,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Aura',NULL),
    ('C107','bloodspill-invocation-2','Bloodspill Invocation',2,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Aura',NULL),
    ('C108','bloodspill-invocation-3','Bloodspill Invocation',3,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Aura',NULL),
    ('C109','read-the-runes-1','Read the Runes',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('C110','read-the-runes-2','Read the Runes',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('C111','read-the-runes-3','Read the Runes',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('C112','runechant','Runechant',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Runeblade','Token','Aura',NULL),
    ('C113','kano-dracai-of-aether','Kano, Dracai of Aether',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,30,NULL,'N','Wizard','Hero',NULL,NULL),
    ('C114','kano','Kano',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,15,NULL,'N','Wizard','Hero','Young',NULL),
    ('C115','crucible-of-aetherweave','Crucible of Aetherweave',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,'N','Wizard','Weapon','Staff',NULL),
    ('C116','storm-striders','Storm Striders',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Wizard','Equipment','Legs',NULL),
    ('C117','robe-of-rapture','Robe of Rapture',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Wizard','Equipment','Chest',NULL),
    ('C118','blazing-aether-1','Blazing Aether',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,'Kano'),
    ('C119','sonic-boom-2','Sonic Boom',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C120','forked-lightning-1','Forked Lightning',1,3,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C121','lesson-in-lava-2','Lesson in Lava',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,'Kano'),
    ('C122','tome-of-aetherwind-1','Tome of Aetherwind',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C123','absorb-in-aether-1','Absorb in Aether',1,1,NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,'N','Wizard','Defense Reaction',NULL,NULL),
    ('C124','absorb-in-aether-2','Absorb in Aether',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Defense Reaction',NULL,NULL),
    ('C125','absorb-in-aether-3','Absorb in Aether',3,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Wizard','Defense Reaction',NULL,NULL),
    ('C126','aether-spindle-1','Aether Spindle',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C127','aether-spindle-2','Aether Spindle',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C128','aether-spindle-3','Aether Spindle',3,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C129','stir-the-aetherwinds-1','Stir the Aetherwinds',1,2,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C130','stir-the-aetherwinds-2','Stir the Aetherwinds',2,2,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C131','stir-the-aetherwinds-3','Stir the Aetherwinds',3,2,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C132','aether-flare-1','Aether Flare',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C133','aether-flare-2','Aether Flare',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C134','aether-flare-3','Aether Flare',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C135','index-1','Index',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C136','index-2','Index',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C137','index-3','Index',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C138','reverberate-1','Reverberate',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C139','reverberate-2','Reverberate',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C140','reverberate-3','Reverberate',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C141','scalding-rain-1','Scalding Rain',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C142','scalding-rain-2','Scalding Rain',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C143','scalding-rain-3','Scalding Rain',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C144','zap-1','Zap',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C145','zap-2','Zap',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C146','zap-3','Zap',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C147','voltic-bolt-1','Voltic Bolt',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C148','voltic-bolt-2','Voltic Bolt',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C149','voltic-bolt-3','Voltic Bolt',3,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('C150','arcanite-skullcap','Arcanite Skullcap',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Generic','Equipment',NULL,NULL),
    ('C151','talismanic-lens','Talismanic Lens',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Head',NULL),
    ('C152','vest-of-the-first-fist','Vest of the First Fist',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Chest',NULL),
    ('C153','bracers-of-belief','Bracers of Belief',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Arms',NULL),
    ('C154','mage-master-boots','Mage Master Boots',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Legs',NULL),
    ('C155','nullrune-hood','Nullrune Hood',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Head',NULL),
    ('C156','nullrune-robe','Nullrune Robe',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Chest',NULL),
    ('C157','nullrune-gloves','Nullrune Gloves',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Arms',NULL),
    ('C158','nullrune-boots','Nullrune Boots',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Legs',NULL),
    ('C159','command-and-conquer-1','Command and Conquer',1,2,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C160','art-of-war-2','Art of War',2,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('C161','pursuit-of-knowledge-3','Pursuit of Knowledge',3,2,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C162','chains-of-eminence-1','Chains of Eminence',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Aura',NULL),
    ('C163','rusted-relic-3','Rusted Relic',3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Action','Item',NULL),
    ('C164','life-for-a-life-1','Life for a Life',1,1,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C165','life-for-a-life-2','Life for a Life',2,1,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C166','life-for-a-life-3','Life for a Life',3,1,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C167','enchanting-melody-1','Enchanting Melody',1,2,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C168','enchanting-melody-2','Enchanting Melody',2,2,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C169','enchanting-melody-3','Enchanting Melody',3,2,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C170','plunder-run-1','Plunder Run',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C171','plunder-run-2','Plunder Run',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C172','plunder-run-3','Plunder Run',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C173','eirinas-prayer-1','Eirina''s Prayer',1,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('C174','eirinas-prayer-2','Eirina''s Prayer',2,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('C175','eirinas-prayer-3','Eirina''s Prayer',3,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('C176','back-alley-breakline-1','Back Alley Breakline',1,1,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C177','back-alley-breakline-2','Back Alley Breakline',2,1,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C178','back-alley-breakline-3','Back Alley Breakline',3,1,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C179','cadaverous-contraband-1','Cadaverous Contraband',1,2,NULL,6,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C180','cadaverous-contraband-2','Cadaverous Contraband',2,2,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C181','cadaverous-contraband-3','Cadaverous Contraband',3,2,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C182','fervent-forerunner-1','Fervent Forerunner',1,0,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C183','fervent-forerunner-2','Fervent Forerunner',2,0,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C184','fervent-forerunner-3','Fervent Forerunner',3,0,NULL,1,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C185','moon-wish-1','Moon Wish',1,2,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C186','moon-wish-2','Moon Wish',2,2,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C187','moon-wish-3','Moon Wish',3,2,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C188','push-the-point-1','Push the Point',1,1,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C189','push-the-point-2','Push the Point',2,1,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C190','push-the-point-3','Push the Point',3,1,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C191','ravenous-rabble-1','Ravenous Rabble',1,0,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C192','ravenous-rabble-2','Ravenous Rabble',2,0,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C193','ravenous-rabble-3','Ravenous Rabble',3,0,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C194','rifting-1','Rifting',1,2,NULL,6,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C195','rifting-2','Rifting',2,2,NULL,5,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C196','rifting-3','Rifting',3,2,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C197','vigor-rush-1','Vigor Rush',1,1,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C198','vigor-rush-2','Vigor Rush',2,1,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C199','vigor-rush-3','Vigor Rush',3,1,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('C200','fate-forseen-1','Fate Forseen',1,0,NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,'N','Generic','Defense Reaction',NULL,NULL),
    ('C201','fate-forseen-2','Fate Forseen',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Defense Reaction',NULL,NULL),
    ('C202','fate-forseen-3','Fate Forseen',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Defense Reaction',NULL,NULL),
    ('C203','come-to-fight-1','Come to Fight',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C204','come-to-fight-2','Come to Fight',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C205','come-to-fight-3','Come to Fight',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C206','force-sight-1','Force Sight',1,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C207','force-sight-2','Force Sight',2,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C208','force-sight-3','Force Sight',3,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C209','lead-the-charge-1','Lead the Charge',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C210','lead-the-charge-2','Lead the Charge',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C211','lead-the-charge-3','Lead the Charge',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C212','sun-kiss-1','Sun Kiss',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C213','sun-kiss-2','Sun Kiss',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C214','sun-kiss-3','Sun Kiss',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C215','whisper-of-the-oracle-1','Whisper of the Oracle',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C216','whisper-of-the-oracle-2','Whisper of the Oracle',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('C217','whisper-of-the-oracle-3','Whisper of the Oracle',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('Z001','go-bananas-2','Go Banana''s',2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('D001','arknight-shard-3','Arknight Shard',3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'t','Generic','Resource','Gem','Viserai'),
    ('D002','kayo-beserker-runt','Kayo, Beserker Runt',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,19,NULL,'N','Brute','Hero','Young',NULL),
    ('D003','mandible-claw','Mandible Claw',NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL,1,'N','Brute','Weapon','Claw',NULL),
    ('D004','skullhorn','Skullhorn',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Brute','Equipment','Head',NULL),
    ('D005','beast-within-2','Beast Within',2,3,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D006','massacre-1','Massacre',1,3,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D007','argh-smash-2','Argh... Smash!',2,3,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action',NULL,NULL),
    ('D008','barraging-big-horn-1','Barraging Big Horn',1,2,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D009','barraging-big-horn-2','Barraging Big Horn',2,2,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D010','barraging-big-horn-3','Barraging Big Horn',3,2,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D011','predatory-assault-1','Predatory Assault',1,2,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D012','predatory-assault-2','Predatory Assault',2,2,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D013','predatory-assault-3','Predatory Assault',3,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D014','riled-up-1','Riled Up',1,3,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D015','riled-up-2','Riled Up',2,3,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D016','riled-up-3','Riled Up',3,3,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D017','swing-fist-think-later-1','Swing Fist, Think Later',1,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D018','swing-fist-think-later-2','Swing Fist, Think Later',2,1,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D019','swing-fist-think-later-3','Swing Fist, Think Later',3,1,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Brute','Action','Attack',NULL),
    ('D020','sledge-of-anvilheim','Sledge of Anvilheim',NULL,NULL,NULL,6,NULL,NULL,NULL,NULL,NULL,2,'N','Guardian','Weapon','Hammer',NULL),
    ('D021','crater-fist','Crater Fist',NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Guardian','Equipment','Arms',NULL),
    ('D022','mangle-1','Mangle',1,4,NULL,8,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('D023','righteous-cleansing-2','Righteous Cleansing',2,7,NULL,10,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('D024','stamp-authority-3','Stamp Authority',3,3,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action',NULL,NULL),
    ('D025','towering-titan-1','Towering Titan',1,9,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('D026','towering-titan-2','Towering Titan',2,9,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('D027','towering-titan-3','Towering Titan',3,9,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('D028','crush-the-weak-1','Crush the Weak',1,3,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('D029','crush-the-weak-2','Crush the Weak',2,3,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('D030','crush-the-weak-3','Crush the Weak',3,3,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('D031','chokeslam-1','Chokeslam',1,4,NULL,8,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('D032','chokeslam-2','Chokeslam',2,4,NULL,7,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('D033','chokeslam-3','Chokeslam',3,4,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Attack',NULL),
    ('D034','emerging-dominance-1','Emerging Dominance',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('D035','emerging-dominance-2','Emerging Dominance',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('D036','emerging-dominance-3','Emerging Dominance',3,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Guardian','Action','Aura',NULL),
    ('D037','blessing-of-serenity-1','Blessing of Serenity',1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Guardian','Instant',NULL,NULL),
    ('D038','blessing-of-serenity-2','Blessing of Serenity',2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Guardian','Instant',NULL,NULL),
    ('D039','blessing-of-serenity-3','Blessing of Serenity',3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Guardian','Instant',NULL,NULL),
    ('D040','benji-the-piercing-wind','Benji, the Piercing Wind',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,17,NULL,'N','Ninja','Hero','Young',NULL),
    ('D041','zephyr-needle','Zephyr Needle',NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,1,'N','Ninja','Weapon','Dagger',NULL),
    ('D042','breeze-rider-boots','Breeze Rider Boots',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,'N','Ninja','Equipment','Legs',NULL),
    ('D043','find-center-3','Find Center',3,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D044','flood-of-force-2','Flood of Force',2,0,NULL,1,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D045','herons-flight-1','Heron''s Flight',1,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL);
INSERT INTO "temp_card_templates" VALUES
    ('D046','crane-dance-1','Crane Dance',1,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D047','crane-dance-2','Crane Dance',2,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D048','crane-dance-3','Crane Dance',3,0,NULL,1,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D049','rushing-river-1','Rushing River',1,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D050','rushing-river-2','Rushing River',2,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D051','rushing-river-3','Rushing River',3,0,NULL,1,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D052','flying-kick-2','Flying Kick',2,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D053','flying-kick-3','Flying Kick',3,2,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D054','soulbead-strike-1','Soulbead Strike',1,0,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D055','soulbead-strike-2','Soulbead Strike',2,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D056','soulbead-strike-3','Soulbead Strike',3,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D057','torrent-of-tempo-2','Torrent of Tempo',2,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D058','torrent-of-tempo-3','Torrent of Tempo',3,1,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ninja','Action','Attack',NULL),
    ('D059','zen-state','Zen State',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Ninja','Token','Aura',NULL),
    ('D060','kassai-cintari-sellsword','Kassai, Cintari Sellsword',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,20,NULL,'N','Warrior','Hero','Young',NULL),
    ('D061','cintari-saber','Cintari Saber',NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,1,'N','Warrior','Weapon','Sword',NULL),
    ('D062','courage-of-bladehold','Courage of Bladehold',NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Warrior','Equipment','Chest',NULL),
    ('D063','twinning-blade-2','Twinning Blade',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('D064','unified-decree-2','Unified Decree',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('D065','spoils-of-war-1','Spoils of War',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('D066','dauntless-1','Dauntless',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('D067','dauntless-2','Dauntless',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('D068','dauntless-3','Dauntless',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('D069','out-for-blood-1','Out for Blood',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('D070','out-for-blood-2','Out for Blood',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('D071','out-for-blood-3','Out for Blood',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Attack Reaction',NULL,NULL),
    ('D072','hit-and-run-1','Hit and Run',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('D073','hit-and-run-2','Hit and Run',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('D074','hit-and-run-3','Hit and Run',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('D075','push-forward-1','Push Forward',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('D076','push-forward-2','Push Forward',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('D077','push-forward-3','Push Forward',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Warrior','Action',NULL,NULL),
    ('D078','shiyana-diamond-gemini','Shiyana, Diamond Gemini',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,20,NULL,'N','Shapeshifter','Hero','Young',NULL),
    ('D079','data-doll-mkii','Data Doll MKII',NULL,NULL,NULL,NULL,NULL,NULL,NULL,3,20,NULL,'N','Mechanologist','Hero','Young',NULL),
    ('D080','plasma-barrel-shot','Plasma Barrel Shot',NULL,NULL,NULL,NULL,'X',NULL,NULL,NULL,NULL,2,'N','Mechanologist','Weapon','Gun',NULL),
    ('D081','viziertronic-model-i','Viziertronic Model i',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Mechanologist','Equipment','Head',NULL),
    ('D082','meganetic-shockwave-3','Meganetic Shockwave',3,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('D083','absorbtion-dome-2','Absorbtion Dome',2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Item',NULL),
    ('D084','plasma-purifier-1','Plasma Purifier',1,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Item',NULL),
    ('D085','high-speed-impact-1','High Speed Impact',1,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('D086','high-speed-impact-2','High Speed Impact',2,1,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('D087','high-speed-impact-3','High Speed Impact',3,1,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('D088','combustible-courier-1','Combustible Courier',1,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('D089','combustible-courier-2','Combustible Courier',2,2,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('D090','combustible-courier-3','Combustible Courier',3,2,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('D091','overblast-1','Overblast',1,2,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('D092','overblast-2','Overblast',2,2,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('D093','overblast-3','Overblast',3,2,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action','Attack',NULL),
    ('D094','teklovossens-workshop-1','Teklovossen''s Workshop',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action',NULL,NULL),
    ('D095','teklovossens-workshop-2','Teklovossen''s Workshop',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action',NULL,NULL),
    ('D096','teklovossens-workshop-3','Teklovossen''s Workshop',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Mechanologist','Action',NULL,NULL),
    ('D097','kavdaen-trader-of-skins','Kavdaen, Trader of Skins',NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,20,NULL,'N','Merchant','Hero','Young',NULL),
    ('D098','red-liner','Red Liner',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Ranger','Weapon','Bow',NULL),
    ('D099','perch-grapplers','Perch Grapplers',NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Equipment','Legs',NULL),
    ('D100','remorseless-1','Remorseless',1,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('D101','poison-the-tips-2','Poison the Tips',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('D102','feign-death-2','Feign Death',2,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Ranger','Instant',NULL,NULL),
    ('D103','tripwire-trap-1','Tripwire Trap',1,0,NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,'N','Ranger','Defense Reaction','Trap',NULL),
    ('D104','pitfall-trap-2','Pitfall Trap',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Defense Reaction','Trap',NULL),
    ('D105','rockslide-trap-3','Rockslide Trap',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Defense Reaction','Trap',NULL),
    ('D106','pathing-helix-1','Pathing Helix',1,0,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('D107','pathing-helix-2','Pathing Helix',2,0,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('D108','pathing-helix-3','Pathing Helix',3,0,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('D109','sleep-dart-1','Sleep Dart',1,1,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('D110','sleep-dart-2','Sleep Dart',2,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('D111','sleep-dart-3','Sleep Dart',3,1,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Ranger','Action','Arrow,Attack',NULL),
    ('D112','increase-the-tension-1','Increase the Tension',1,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('D113','increase-the-tension-2','Increase the Tension',2,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('D114','increase-the-tension-3','Increase the Tension',3,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Ranger','Action',NULL,NULL),
    ('D115','reaping-blade','Reaping Blade',NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL,2,'N','Runeblade','Weapon','Sword',NULL),
    ('D116','bloodsheath-skeleta','Bloodsheath Skeleta',NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Equipment','Chest',NULL),
    ('D117','dread-triptych-3','Dread Triptych',3,3,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('D118','rattle-bones-1','Rattle Bones',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('D119','runeblood--barrier-2','Runeblood  Barrier',2,3,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Aura',NULL),
    ('D120','mauvrion-skies-1','Mauvrion Skies',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('D121','mauvrion-skies-2','Mauvrion Skies',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('D122','mauvrion-skies-3','Mauvrion Skies',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('D123','consuming-volition-1','Consuming Volition',1,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('D124','consuming-volition-2','Consuming Volition',2,1,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('D125','consuming-volition-3','Consuming Volition',3,1,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('D126','meat-and-greet-1','Meat and Greet',1,1,NULL,4,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('D127','meat-and-greet-2','Meat and Greet',2,1,NULL,3,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('D128','meat-and-greet-3','Meat and Greet',3,1,NULL,2,NULL,3,NULL,NULL,NULL,NULL,'N','Runeblade','Action','Attack',NULL),
    ('D129','sutcliffes-research-notes-1','Sutcliffe''s Research Notes',1,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('D130','sutcliffes-research-notes-2','Sutcliffe''s Research Notes',2,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('D131','sutcliffes-research-notes-3','Sutcliffe''s Research Notes',3,1,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Runeblade','Action',NULL,NULL),
    ('D132','aether-conduit','Aether Conduit',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,'N','Wizard','Weapon','Staff',NULL),
    ('D133','metacarpus-node','Metacarpus Node',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Wizard','Equipment','Arms',NULL),
    ('D134','chain-lightning-2','Chain Lightning',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D135','gaze-the-ages-3','Gaze the Ages',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D136','aetherize-3','Aetherize',3,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Wizard','Instant',NULL,NULL),
    ('D137','cindering-foresight-1','Cindering Foresight',1,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D138','cindering-foresight-2','Cindering Foresight',2,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D139','cindering-foresight-3','Cindering Foresight',3,0,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D140','foreboding-bolt-1','Foreboding Bolt',1,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D141','foreboding-bolt-2','Foreboding Bolt',2,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D142','foreboding-bolt-3','Foreboding Bolt',3,1,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D143','rousing-aether-1','Rousing Aether',1,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D144','rousing-aether-2','Rousing Aether',2,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D145','rousing-aether-3','Rousing Aether',3,2,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D146','snapback-1','Snapback',1,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D147','snapback-2','Snapback',2,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D148','snapback-3','Snapback',3,0,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,'N','Wizard','Action',NULL,NULL),
    ('D149','talishar-the-lost-prince','Talishar, the Lost Prince',NULL,NULL,NULL,4,NULL,NULL,NULL,NULL,NULL,2,'N','Generic','Weapon','Sword',NULL),
    ('D150','gamblers-gloves','Gambler''s Gloves',NULL,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,'N','Generic','Equipment','Arms',NULL),
    ('D151','coax-a-commotion-1','Coax a Commotion',1,0,NULL,4,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('D152','gorganian-tome','Gorganian Tome',NULL,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'t','Generic','Action',NULL,NULL),
    ('D153','snag-3','Snag',3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('D154','promise-of-plenty-1','Promise of Plenty',1,0,NULL,3,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('D155','promise-of-plenty-2','Promise of Plenty',2,0,NULL,2,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('D156','promise-of-plenty-3','Promise of Plenty',3,0,NULL,1,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('D157','cash-in-2','Cash In',2,4,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,'N','Generic','Action',NULL,NULL),
    ('D158','reinforce-the-line-1','Reinforce the Line',1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('D159','reinforce-the-line-2','Reinforce the Line',2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('D160','reinforce-the-line-3','Reinforce the Line',3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Instant',NULL,NULL),
    ('D161','brutal-assault-1','Brutal Assault',1,2,NULL,6,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('D162','brutal-assault-2','Brutal Assault',2,2,NULL,5,NULL,3,NULL,NULL,NULL,NULL,'N','Generic','Action','Attack',NULL),
    ('D163','copper','Copper',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'N','Generic','Token','Item',NULL);
